# Generated by Django 4.2.3 on 2023-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=''),
        ),
    ]
